### ISSUE TITLE
The formula number will report an error after refreshing in Ms Word

### ISSUE THREAD

**Issue by wenbopeng** [tstenner/luarefnos#2]
```Markdown
Equations, such as @eq:pythagoras , have to be put into a span with an id:

[$$a^2 + b^2 = c^2$$]{#eq:pythagoras}
```

![image](https://github.com/tstenner/luarefnos/assets/74350447/9c9a90e6-155d-4765-9c82-4cb2a9a4ef6b)

![image](https://github.com/tstenner/luarefnos/assets/74350447/58778db2-204d-4698-8a6a-247e4443425b)

If you change the field code to match the bookmark, another error occurs: 

![image](https://github.com/tstenner/luarefnos/assets/74350447/2ff35c38-5dd9-405a-97fc-fab847a76940)

**Comment by wenbopeng** [comment]
By the way, can the syntax of formula numbering be more elegant? Refer to `pandoc-crossref`:

```Markdown
Equations, such as @eq:pythagoras , have to be put into a span with an id:

$$
a^2 + b^2 = c^2
$$
{#eq:pythagoras}
```

or

```Markdown
Equations, such as @eq:pythagoras , have to be put into a span with an id:

$$a^2 + b^2 = c^2$${#eq:pythagoras}
```

Of course, this may be related to the difficulty of Lua, just for reference

**Comment by tstenner** [comment]
I added some changes to append the equation number in docx documents. The references don't add the "equation" prefix (yet), but it'S a first step.

I haven't found a better way to write the equation numbers, because spans (the `[]` brackets) with ids have their attributes (i.e. the id) parsed by pandoc, so the lua reader just has to refer to the id field instead of parsing the entire text for labelled equations.

**Comment by wenbopeng** [comment]
Thank you for your quick response. It is already great.

**Comment by wenbopeng** [comment]
This issue has been solved,I think this topic can be closed. Thanks for your work.
